[theme]
# Colores del tema personalizado para un look más suave

#Color de Fondo Principal de la Página
backgroundColor="#51306E"

#Color de Fondo de la Barra Lateral y Contenedores (como la expander)
secondaryBackgroundColor="#B08ECD" 

#Color Primario (para botones, sliders, etc.)
primaryColor="#FF69B4" 

#Color del Texto
textColor="#333333"

#Puedes añadir una fuente si quieres
font="sans-serif"
